### ISSUE TITLE
SHACL for bibliographic records

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-marc#209]

**Comment by pkiraly** [comment]
```YAML
- name: 040$a
  path: 040$a
  rules:
    - minCount: 1
    - pattern: BE-KBR00
```
